name: movies
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+42

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.4.0
  json_store: ^2.0.2
  flutter_rating: ^2.0.2 
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  firebase_messaging: ^16.0.0
  firebase_auth: ^6.0.0
  logger: ^2.6.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  youtube_player_flutter: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^19.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/