// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGqDZIQLLyS47WP9AU-UiD7me2R34uMtM',
    appId: '1:816692756307:android:f2c0d02a6e25727d6deba6',
    messagingSenderId: '816692756307',
    projectId: 'movies-1430c',
    databaseURL: 'https://movies-1430c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'movies-1430c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ1SV8PDKgQKGKAb8ZDEqE88sW8sR_FFU',
    appId: '1:816692756307:ios:598788956b7d3a556deba6',
    messagingSenderId: '816692756307',
    projectId: 'movies-1430c',
    databaseURL: 'https://movies-1430c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'movies-1430c.firebasestorage.app',
    iosBundleId: 'com.movies2.ios',
  );

}